// ISO 3166-1 alpha-2 country list with human-readable names.
// Trimmed list — 100 most common countries plus "Other".
// Used for KYC jurisdiction selection.

export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: "HK", name: "Hong Kong SAR" },
  { code: "SG", name: "Singapore" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" },
  { code: "HR", name: "Croatia" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GT", name: "Guatemala" },
  { code: "HN", name: "Honduras" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KR", name: "South Korea" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao SAR" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "Mexico" },
  { code: "MD", name: "Moldova" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MM", name: "Myanmar" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "RS", name: "Serbia" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "ZA", name: "South Africa" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
  { code: "OTHER", name: "Other / Not listed" },
];

// Quick lookup by code
export const COUNTRY_MAP: Record<string, string> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c.name])
);

// ---------------------------------------------------------------------------
// Sumsub integration — needs ISO 3166-1 alpha-3 codes, not the alpha-2 codes
// used by the OCR flow above. Map the most common alpha-2 → alpha-3 codes so a
// single dropdown value can drive both.
// ---------------------------------------------------------------------------
export const ALPHA2_TO_ALPHA3: Record<string, string> = {
  HK: "HKG", SG: "SGP", AE: "ARE", US: "USA", GB: "GBR",
  AU: "AUS", AT: "AUT", BE: "BEL", BR: "BRA", CA: "CAN",
  CH: "CHE", CL: "CHL", CN: "CHN", CO: "COL", CZ: "CZE",
  DE: "DEU", DK: "DNK", EG: "EGY", ES: "ESP", EE: "EST",
  FI: "FIN", FR: "FRA", GH: "GHA", GR: "GRC", HU: "HUN",
  ID: "IDN", IN: "IND", IE: "IRL", IL: "ISR", IT: "ITA",
  JP: "JPN", KE: "KEN", KR: "KOR", LT: "LTU", LU: "LUX",
  LV: "LVA", MX: "MEX", MY: "MYS", NG: "NGA", NL: "NLD",
  NO: "NOR", NZ: "NZL", PK: "PAK", PE: "PER", PH: "PHL",
  PL: "POL", PT: "PRT", RO: "ROU", SA: "SAU", SE: "SWE",
  TH: "THA", TR: "TUR", TW: "TWN", UA: "UKR", VN: "VNM",
  ZA: "ZAF", AR: "ARG", BD: "BGD", VE: "VEN", RU: "RUS",
  AF: "AFG", AL: "ALB", DZ: "DZA", AO: "AGO", AM: "ARM",
  AZ: "AZE", BH: "BHR", BY: "BLR", BO: "BOL", BA: "BIH",
  BG: "BGR", KH: "KHM", CM: "CMR", CI: "CIV", HR: "HRV",
  CY: "CYP", DO: "DOM", EC: "ECU", ET: "ETH", GE: "GEO",
  GT: "GTM", HN: "HND", IS: "ISL", IR: "IRN", IQ: "IRQ",
  JM: "JAM", JO: "JOR", KZ: "KAZ", KW: "KWT", KG: "KGZ",
  LB: "LBN", LY: "LBY", MK: "MKD", MG: "MDG", MW: "MWI",
  MT: "MLT", MA: "MAR", MM: "MMR", NP: "NPL", NI: "NIC",
  OM: "OMN", PY: "PRY", QA: "QAT", RW: "RWA", SN: "SEN",
  RS: "SRB", SK: "SVK", SI: "SVN", LK: "LKA", SD: "SDN",
  SY: "SYR", TJ: "TJK", TZ: "TZA", TN: "TUN", UG: "UGA",
  UY: "URY", UZ: "UZB", YE: "YEM", ZM: "ZMB", ZW: "ZWE",
};

/** Convert an alpha-2 country code to alpha-3 for Sumsub. Returns undefined for
 *  unmapped codes (including "OTHER") so callers can omit the field. */
export function toAlpha3(alpha2: string | undefined): string | undefined {
  if (!alpha2) return undefined;
  return ALPHA2_TO_ALPHA3[alpha2.toUpperCase()];
}

/** Default country selection in the KYC picker — matches HashKey's home market. */
export const DEFAULT_COUNTRY = "HK";
